DROP TABLE abonnement CASCADE CONSTRAINTS;
DROP TABLE favoris CASCADE CONSTRAINTS;
DROP TABLE historique CASCADE CONSTRAINTS;
DROP TABLE preference CASCADE CONSTRAINTS;
DROP TABLE utilisateur CASCADE CONSTRAINTS;
DROP TABLE episode CASCADE CONSTRAINTS;
DROP TABLE varchive CASCADE CONSTRAINTS;
DROP TABLE video CASCADE CONSTRAINTS;
DROP TABLE diffusion CASCADE CONSTRAINTS;
DROP TABLE emission CASCADE CONSTRAINTS;
DROP TABLE categorie CASCADE CONSTRAINTS;

DROP SEQUENCE cat;
DROP SEQUENCE emi;
DROP SEQUENCE vid;
DROP SEQUENCE epi;
DROP SEQUENCE uti;
DROP SEQUENCE dif;