INSERT INTO categorie VALUES (cat.nextval, 'Cinéma', 'Vous venez de rater la première de votre magazine cinéma préféré ? Retrouvez l''émission complète dans la catégorie Cinéma !');
  INSERT INTO emission VALUES (emi.nextval, cat.currval,'Personne ne bouge!', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'arte');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 1', 'Lorem ipsum dolor sit amet.', 35, TO_DATE('25/09/2016', 'DD/MM/YYYY'), 'France', SYSDATE+3, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-4);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 2', 'Lorem ipsum dolor sit amet.', 35, TO_DATE('02/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+4, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 2, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-3);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 3', 'Lorem ipsum dolor sit amet.', 35, TO_DATE('09/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 3, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 4', 'Lorem ipsum dolor sit amet.', 35, TO_DATE('16/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+6, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 4, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-1);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 5', 'Lorem ipsum dolor sit amet.', 35, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 5, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);

  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Le Grand Frisson', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'CANAL+');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 1', 'Lorem ipsum dolor sit amet.', 10, TO_DATE('18/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+2, DEFAULT);
        INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
        INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-5);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 2', 'Lorem ipsum dolor sit amet.', 10, TO_DATE('19/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+3, DEFAULT);
        INSERT INTO episode VALUES (epi.nextval, 2, vid.currval, emi.currval);
        INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-4);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 3', 'Lorem ipsum dolor sit amet.', 10, TO_DATE('20/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+4, DEFAULT);
        INSERT INTO episode VALUES (epi.nextval, 3, vid.currval, emi.currval);
        INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-3);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 4', 'Lorem ipsum dolor sit amet.', 10, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+5, DEFAULT);
        INSERT INTO episode VALUES (epi.nextval, 4, vid.currval, emi.currval);
        INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 5', 'Lorem ipsum dolor sit amet.', 10, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+6, DEFAULT);
        INSERT INTO episode VALUES (epi.nextval, 5, vid.currval, emi.currval);
        INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-1);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 6', 'Lorem ipsum dolor sit amet.', 10, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
        INSERT INTO episode VALUES (epi.nextval, 6, vid.currval, emi.currval);
        INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Cinésix', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'M6');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 1', 'Lorem ipsum dolor sit amet.', 2, TO_DATE('18/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE-3, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-10);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 2', 'Lorem ipsum dolor sit amet.', 2, TO_DATE('18/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE-2, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 2, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-9);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 3', 'Lorem ipsum dolor sit amet.', 2, TO_DATE('19/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE-1, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 3, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-8);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 4', 'Lorem ipsum dolor sit amet.', 2, TO_DATE('19/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 4, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-7);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 5', 'Lorem ipsum dolor sit amet.', 2, TO_DATE('20/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+1, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 5, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-6);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 6', 'Lorem ipsum dolor sit amet.', 2, TO_DATE('20/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+2, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 6, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-5);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 7', 'Lorem ipsum dolor sit amet.', 2, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+3, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 7, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-4);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 8', 'Lorem ipsum dolor sit amet.', 2, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+4, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 8, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-3);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 9', 'Lorem ipsum dolor sit amet.', 2, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 9, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 10', 'Lorem ipsum dolor sit amet.', 2, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+6, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 10, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Pop up', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'C8');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 1', 'Lorem ipsum dolor sit amet.', 46, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+6, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-1);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 2', 'Lorem ipsum dolor sit amet.', 46, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 2, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);

INSERT INTO categorie VALUES (cat.nextval, 'Documentaire', 'Pour revoir tout bon documentaire vu à la télé c''est ici');
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'La cabane de mes rêves', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'France 5');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 1', 'Lorem ipsum dolor sit amet.', 50, TO_DATE('20/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+3, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-4);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 2', 'Lorem ipsum dolor sit amet.', 50, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 2, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 3', 'Lorem ipsum dolor sit amet.', 50, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 3, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Prisonniers des glaces', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'RMC');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 1', 'Lorem ipsum dolor sit amet.', 45, TO_DATE('19/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+4, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-3);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 2', 'Lorem ipsum dolor sit amet.', 45, TO_DATE('20/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 2, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 3', 'Lorem ipsum dolor sit amet.', 45, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+6, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 3, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-1);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 4', 'Lorem ipsum dolor sit amet.', 45, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 4, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Le dessous des cartes', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'arte');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 1', 'Lorem ipsum dolor sit amet.', 12, TO_DATE('16/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+1, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-6);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 2', 'Lorem ipsum dolor sit amet.', 12, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+4, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 2, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-3);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Points de repères', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'arte');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 1', 'Lorem ipsum dolor sit amet.', 54, TO_DATE('09/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 2', 'Lorem ipsum dolor sit amet.', 54, TO_DATE('16/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+6, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 2, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-1);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 3', 'Lorem ipsum dolor sit amet.', 54, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 3, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Comment Bach a vaincu Mao', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'arte');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Comment Bach a vaincu Mao', 'Lorem ipsum dolor sit amet.', 120, TO_DATE('20/10/2016', 'DD/MM/YYYY'), 'Allemagne', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Sur les pas de Beethoven', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'France 5');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Sur les pas de Beethoven', 'Lorem ipsum dolor sit amet.', 60, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'Allemagne', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Alien theory V', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'RMC');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 7', 'Lorem ipsum dolor sit amet.', 45, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'Etats-Unis', SYSDATE+1, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 7, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-6);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 8', 'Lorem ipsum dolor sit amet.', 45, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'Etats-Unis', SYSDATE+4, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 8, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-3);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 9', 'Lorem ipsum dolor sit amet.', 45, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'Etats-Unis', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 9, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);

INSERT INTO categorie VALUES (cat.nextval, 'Musique', 'Toutes les nouveautés dans le monde de la musique française et internationale.');
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Génération hit machine', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'W9');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 329', 'Lorem ipsum dolor sit amet.', 22, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 329, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 330', 'Lorem ipsum dolor sit amet.', 22, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+6, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 330, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-1);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 331', 'Lorem ipsum dolor sit amet.', 22, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 331, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Le Requiem de Berlioz', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'arte');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Le Requiem de Berlioz', 'Lorem ipsum dolor sit amet.', 180, TO_DATE('20/10/2016', 'DD/MM/YYYY'), 'Belgique', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Alcaline', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'France 2');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 22', 'Lorem ipsum dolor sit amet.', 35, TO_DATE('20/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+3, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 22, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-4);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 23', 'Lorem ipsum dolor sit amet.', 35, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 23, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);

INSERT INTO categorie VALUES (cat.nextval, 'Séries', 'Ne ratez plus jamais aucun épisode de votre série préférée. La catégorie Séries contient les derniers épisodes de toutes les séries diffusées sur les chaîne de la TNT.');
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Les enquêtes de Murdoch X', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'France 3');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 1', 'Lorem ipsum dolor sit amet.', 45, TO_DATE('15/10/2016', 'DD/MM/YYYY'), 'Canada', SYSDATE+2, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-5);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 2', 'Lorem ipsum dolor sit amet.', 45, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'Canada', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 2, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Les experts Miami XV', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'M6');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 15', 'Lorem ipsum dolor sit amet.', 51, TO_DATE('20/10/2016', 'DD/MM/YYYY'), 'Etats-Unis', SYSDATE+1, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 15, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-6);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 16', 'Lorem ipsum dolor sit amet.', 51, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'Etats-Unis', SYSDATE+3, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 16, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-4);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 17', 'Lorem ipsum dolor sit amet.', 51, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'Etats-Unis', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 17, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 18', 'Lorem ipsum dolor sit amet.', 51, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'Etats-Unis', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 18, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Les Simpsons XXVII', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'W9');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 8', 'Lorem ipsum dolor sit amet.', 21, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'Etats-Unis', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 8, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 9', 'Lorem ipsum dolor sit amet.', 21, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'Etats-Unis', SYSDATE+6, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 9, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-1);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 10', 'Lorem ipsum dolor sit amet.', 21, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'Etats-Unis', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 10, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Face au doute', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', '6ter');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 55', 'Lorem ipsum dolor sit amet.', 60, TO_DATE('16/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+4, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 55, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-3);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 56', 'Lorem ipsum dolor sit amet.', 60, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 56, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Sous les jupons de l''histoire', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'Chérie 25');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'La vie privée de Napoléon Bonaparte', 'Lorem ipsum dolor sit amet.', 52, TO_DATE('16/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+6, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-1);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Les sept femmes de Henri VIII', 'Lorem ipsum dolor sit amet.', 52, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 2, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);

INSERT INTO categorie VALUES (cat.nextval, 'Société', 'Les dernières émissions sur l''économie, l''éducation, la famille, etc. dans une seule catégorie !');
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Les chemins de l''école', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'arte');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 14', 'Lorem ipsum dolor sit amet.', 36, TO_DATE('16/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+4, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 14, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-3);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 15', 'Lorem ipsum dolor sit amet.', 36, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 15, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'L''émission politique', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TV5 Monde');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 987', 'Lorem ipsum dolor sit amet.', 25, TO_DATE('20/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+4, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 987, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-3);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 988', 'Lorem ipsum dolor sit amet.', 25, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 988, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 999', 'Lorem ipsum dolor sit amet.', 25, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+6, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 999, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-1);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 1000', 'Lorem ipsum dolor sit amet.', 25, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1000, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Chroniques criminelles', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'NT1');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 75', 'Lorem ipsum dolor sit amet.', 62, TO_DATE('19/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+3, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 75, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-4);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 76', 'Lorem ipsum dolor sit amet.', 62, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 76, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Episode 77', 'Lorem ipsum dolor sit amet.', 62, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 77, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);

INSERT INTO categorie VALUES (cat.nextval, 'Sport', 'Retrouvez les derniers journaux sportifs, les analyses et les commentaires dans la catégorie Sport!');
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Télé foot', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TF1');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Lorem Ipsum', 'Lorem ipsum dolor sit amet.', 15, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Lorem Ipsum', 'Lorem ipsum dolor sit amet.', 15, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+6, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 2, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-1);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Lorem Ipsum', 'Lorem ipsum dolor sit amet.', 15, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 3, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Sport 6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'M6');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Lorem Ipsum', 'Lorem ipsum dolor sit amet.', 8, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 1, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Lorem Ipsum', 'Lorem ipsum dolor sit amet.', 8, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+6, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 2, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-1);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Lorem Ipsum', 'Lorem ipsum dolor sit amet.', 8, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 3, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);

INSERT INTO categorie VALUES (cat.nextval, 'Technologies', 'Les émissions notamment sur les technologies les plus récentes.');
  INSERT INTO emission VALUES (emi.nextval, cat.currval, 'Culture geek', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'BFMTV');
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Lorem Ipsum', 'Lorem ipsum dolor sit amet.', 26, TO_DATE('18/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+2, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 12, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-5);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Dolor Sit', 'Lorem ipsum dolor sit amet.', 26, TO_DATE('19/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+3, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 13, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-4);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Amet Consecutur', 'Lorem ipsum dolor sit amet.', 26, TO_DATE('20/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+4, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 14, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-3);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Adipiscing Elit', 'Lorem ipsum dolor sit amet.', 26, TO_DATE('21/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+5, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 15, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-2);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Sed Do', 'Lorem ipsum dolor sit amet.', 26, TO_DATE('22/10/2016', 'DD/MM/YYYY'), 'France', SYSDATE+6, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 16, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE-1);
    INSERT INTO video VALUES (vid.nextval, emi.currval, 'Sic Lux', 'Lorem ipsum dolor sit amet.', 26, TO_DATE('23/10/2016', 'DD/MM/YYYY'), 'France', DEFAULT, DEFAULT);
      INSERT INTO episode VALUES (epi.nextval, 17, vid.currval, emi.currval);
      INSERT INTO diffusion VALUES (dif.nextval, vid.currval, SYSDATE);

INSERT INTO utilisateur VALUES (uti.nextval, 'admin', 'Marek', 'Felšöci', '$2y$10$a3gSwLzzqt9uInxAledow.bxogUZ..qrwmuFe9ST3BCGWpUPEOc9C', TO_DATE('23/04/1996', 'DD/MM/YYYY'), 'marek.felsoci@gmail.com', TO_DATE('17/08/2016', 'DD/MM/YYYY'), SYSDATE, 'S', DEFAULT, 'SK');
  INSERT INTO preference VALUES (uti.currval, 1);
  INSERT INTO preference VALUES (uti.currval, 7);
  INSERT INTO historique VALUES (uti.currval, 2, SYSDATE-15);
  INSERT INTO historique VALUES (uti.currval, 52, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 80, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 40, SYSDATE);
  INSERT INTO favoris VALUES (uti.currval, 2);
  INSERT INTO favoris VALUES (uti.currval, 52);
  INSERT INTO favoris VALUES (uti.currval, 80);
  INSERT INTO abonnement VALUES (uti.currval, 22);
  INSERT INTO abonnement VALUES (uti.currval, 1);
INSERT INTO utilisateur VALUES (uti.nextval, 'urig78', 'Görlach', 'Ulrich', '$2y$10$rELFuGnvUK0LpDpapp8KwumD96SyNATT1WwUqemj4uGXzJLKDaR.G', TO_DATE('27/02/1978', 'DD/MM/YYYY'), 'goerlach@cnrs.fr', TO_DATE('20/08/2016', 'DD/MM/YYYY'), SYSDATE, 'A', DEFAULT, 'DE');
  INSERT INTO preference VALUES (uti.currval, 2);
  INSERT INTO preference VALUES (uti.currval, 4);
  INSERT INTO historique VALUES (uti.currval, 5, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 42, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 37, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 80, SYSDATE);
  INSERT INTO favoris VALUES (uti.currval, 5);
  INSERT INTO favoris VALUES (uti.currval, 42);
  INSERT INTO favoris VALUES (uti.currval, 37);
  INSERT INTO favoris VALUES (uti.currval, 80);
  INSERT INTO abonnement VALUES (uti.currval, 12);
  INSERT INTO abonnement VALUES (uti.currval, 15);
INSERT INTO utilisateur VALUES (uti.nextval, 'duri52', 'Jánošík', 'Juraj', '$2y$10$rELFuGnvUK0LpDpapp8KwumD96SyNATT1WwUqemj4uGXzJLKDaR.G', TO_DATE('19/12/1982', 'DD/MM/YYYY'), 'juro.janosik@hotmail.com', TO_DATE('13/09/2016', 'DD/MM/YYYY'), SYSDATE, 'U', DEFAULT, 'SK');
  INSERT INTO preference VALUES (uti.currval, 5);
  INSERT INTO preference VALUES (uti.currval, 7);
  INSERT INTO historique VALUES (uti.currval, 80, SYSDATE-16);
  INSERT INTO historique VALUES (uti.currval, 12, SYSDATE-15);
  INSERT INTO historique VALUES (uti.currval, 14, SYSDATE-12);
  INSERT INTO historique VALUES (uti.currval, 37, SYSDATE-12);
  INSERT INTO favoris VALUES (uti.currval, 80);
  INSERT INTO favoris VALUES (uti.currval, 12);
  INSERT INTO favoris VALUES (uti.currval, 14);
  INSERT INTO favoris VALUES (uti.currval, 37);
  INSERT INTO abonnement VALUES (uti.currval, 20);
  INSERT INTO abonnement VALUES (uti.currval, 17);
INSERT INTO utilisateur VALUES (uti.nextval, 'pysta5', 'Tarhovický', 'Štefan', '$2y$10$rELFuGnvUK0LpDpapp8KwumD96SyNATT1WwUqemj4uGXzJLKDaR.G', TO_DATE('31/10/1992', 'DD/MM/YYYY'), 'pysta.tarhovicky@zoznam.sk', TO_DATE('12/10/2016', 'DD/MM/YYYY'), SYSDATE, 'U', 'Y', 'SK');
  INSERT INTO preference VALUES (uti.currval, 2);
  INSERT INTO preference VALUES (uti.currval, 5);
  INSERT INTO historique VALUES (uti.currval, 2, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 10, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 20, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 30, SYSDATE);
  INSERT INTO favoris VALUES (uti.currval, 2);
  INSERT INTO favoris VALUES (uti.currval, 10);
  INSERT INTO favoris VALUES (uti.currval, 20);
  INSERT INTO abonnement VALUES (uti.currval, 17);
  INSERT INTO abonnement VALUES (uti.currval, 11);
INSERT INTO utilisateur VALUES (uti.nextval, 'pierre756214', 'Lamontagne', 'Pierre', '$2y$10$rELFuGnvUK0LpDpapp8KwumD96SyNATT1WwUqemj4uGXzJLKDaR.G', TO_DATE('15/01/1980', 'DD/MM/YYYY'), 'pierre.lamontagne@laposte.fr', TO_DATE('01/11/2016', 'DD/MM/YYYY'), SYSDATE, 'U', DEFAULT, 'FR');
  INSERT INTO preference VALUES (uti.currval, 1);
  INSERT INTO preference VALUES (uti.currval, 7);
  INSERT INTO historique VALUES (uti.currval, 25, SYSDATE-8);
  INSERT INTO historique VALUES (uti.currval, 79, SYSDATE-7);
  INSERT INTO historique VALUES (uti.currval, 16, SYSDATE-7);
  INSERT INTO historique VALUES (uti.currval, 32, SYSDATE-7);
  INSERT INTO favoris VALUES (uti.currval, 25);
  INSERT INTO favoris VALUES (uti.currval, 79);
  INSERT INTO favoris VALUES (uti.currval, 16);
  INSERT INTO favoris VALUES (uti.currval, 32);
  INSERT INTO abonnement VALUES (uti.currval, 12);
  INSERT INTO abonnement VALUES (uti.currval, 8);
INSERT INTO utilisateur VALUES (uti.nextval, 'martchris', 'Rigoult', 'Christophe', '$2y$10$rELFuGnvUK0LpDpapp8KwumD96SyNATT1WwUqemj4uGXzJLKDaR.G', TO_DATE('14/08/1989', 'DD/MM/YYYY'), 'rigoult@free.fr', TO_DATE('31/08/2016', 'DD/MM/YYYY'), SYSDATE, 'U', DEFAULT, 'FR');
  INSERT INTO preference VALUES (uti.currval, 4);
  INSERT INTO preference VALUES (uti.currval, 5);
  INSERT INTO historique VALUES (uti.currval, 2, SYSDATE-5);
  INSERT INTO historique VALUES (uti.currval, 3, SYSDATE-4);
  INSERT INTO historique VALUES (uti.currval, 4, SYSDATE-4);
  INSERT INTO historique VALUES (uti.currval, 5, SYSDATE-2);
  INSERT INTO favoris VALUES (uti.currval, 2);
  INSERT INTO favoris VALUES (uti.currval, 3);
  INSERT INTO favoris VALUES (uti.currval, 4);
  INSERT INTO favoris VALUES (uti.currval, 5);
  INSERT INTO abonnement VALUES (uti.currval, 1);
  INSERT INTO abonnement VALUES (uti.currval, 25);
INSERT INTO utilisateur VALUES (uti.nextval, 'lery6', 'West', 'Larry', '$2y$10$rELFuGnvUK0LpDpapp8KwumD96SyNATT1WwUqemj4uGXzJLKDaR.G', TO_DATE('06/07/1965', 'DD/MM/YYYY'), 'larryw@yahoo.com', TO_DATE('27/09/2016', 'DD/MM/YYYY'), SYSDATE, 'U', DEFAULT, 'GB');
  INSERT INTO preference VALUES (uti.currval, 5);
  INSERT INTO preference VALUES (uti.currval, 3);
  INSERT INTO historique VALUES (uti.currval, 77, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 70, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 65, SYSDATE-22);
  INSERT INTO historique VALUES (uti.currval, 12, SYSDATE-16);
  INSERT INTO favoris VALUES (uti.currval, 70);
  INSERT INTO favoris VALUES (uti.currval, 12);
  INSERT INTO abonnement VALUES (uti.currval, 3);
INSERT INTO utilisateur VALUES (uti.nextval, 'stabniBrno', 'Jarý', 'Bedřich', '$2y$10$rELFuGnvUK0LpDpapp8KwumD96SyNATT1WwUqemj4uGXzJLKDaR.G', TO_DATE('24/03/1977', 'DD/MM/YYYY'), 'bedrich.jary@gmail.com', TO_DATE('25/08/2016', 'DD/MM/YYYY'), SYSDATE, 'U', 'Y', 'CZ');
  INSERT INTO preference VALUES (uti.currval, 4);
  INSERT INTO preference VALUES (uti.currval, 7);
  INSERT INTO historique VALUES (uti.currval, 32, SYSDATE-1);
  INSERT INTO historique VALUES (uti.currval, 77, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 16, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 14, SYSDATE);
  INSERT INTO abonnement VALUES (uti.currval, 24);
INSERT INTO utilisateur VALUES (uti.nextval, 'JebovicMino', 'Demovič', 'Miňo', '$2y$10$rELFuGnvUK0LpDpapp8KwumD96SyNATT1WwUqemj4uGXzJLKDaR.G', TO_DATE('14/11/1999', 'DD/MM/YYYY'), 'minkoD@azet.sk', TO_DATE('12/10/2016', 'DD/MM/YYYY'), SYSDATE, 'U', DEFAULT, 'SK');
  INSERT INTO preference VALUES (uti.currval, 6);
  INSERT INTO preference VALUES (uti.currval, 7);
  INSERT INTO historique VALUES (uti.currval, 44, SYSDATE-5);
  INSERT INTO historique VALUES (uti.currval, 55, SYSDATE-3);
  INSERT INTO historique VALUES (uti.currval, 66, SYSDATE-3);
  INSERT INTO historique VALUES (uti.currval, 77, SYSDATE-2);
  INSERT INTO favoris VALUES (uti.currval, 55);
  INSERT INTO favoris VALUES (uti.currval, 77);
INSERT INTO utilisateur VALUES (uti.nextval, 'schinke2', 'Schinkel', 'Horst', '$2y$10$rELFuGnvUK0LpDpapp8KwumD96SyNATT1WwUqemj4uGXzJLKDaR.G', TO_DATE('08/08/1988', 'DD/MM/YYYY'), 'schinkelh@post.de', TO_DATE('09/09/2016', 'DD/MM/YYYY'), SYSDATE, 'U', DEFAULT, 'DE');
  INSERT INTO preference VALUES (uti.currval, 2);
  INSERT INTO preference VALUES (uti.currval, 5);
  INSERT INTO historique VALUES (uti.currval, 3, SYSDATE-17);
  INSERT INTO historique VALUES (uti.currval, 79, SYSDATE-2);
  INSERT INTO historique VALUES (uti.currval, 55, SYSDATE);
  INSERT INTO historique VALUES (uti.currval, 66, SYSDATE);
  INSERT INTO favoris VALUES (uti.currval, 79);
  INSERT INTO abonnement VALUES (uti.currval, 22);
  INSERT INTO abonnement VALUES (uti.currval, 23);